version : '3'
services :
  sqlserver:
    image: 192.168.0.104:7071/microsoft/mssql-server-linux:2017
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd123
    ports:
      - "1433:1433"